# Generated by Django 4.1.7 on 2023-03-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_me'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portolio',
            new_name='Portfolio',
        ),
    ]
