# Generated by Django 4.1.7 on 2023-03-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_experienceitems_bottom_color_experienceitems_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('github', models.URLField(blank=True, null=True)),
                ('email', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
