# Generated by Django 4.1.7 on 2023-03-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_medialinks_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
