# Generated by Django 4.1.7 on 2023-03-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
