# Generated by Django 4.1.7 on 2023-03-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hello_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hello',
            new_name='Home',
        ),
    ]
