# Generated by Django 4.1.7 on 2023-03-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_hello_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialinks',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
