# Generated by Django 4.1.7 on 2023-03-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Title',
            },
        ),
        migrations.CreateModel(
            name='ExperienceLevelTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Experience Level Title',
            },
        ),
        migrations.CreateModel(
            name='TestimonialTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Testimonial Title',
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name_plural': 'Experience Title'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Portolio Title'},
        ),
    ]
